export const teas: Tea[] = [
    {
        _id: "1",
        name: "Trà Sen Tây Hồ",
        brand: "Thăng Long",
        images: ["/images/tea/tra-sen-thumb.jpg", "/images/tea/tra-sen-cover.jpg"],
        price: 120000,
        imageThumb: "/images/tea/tra-sen-thumb.png",
        imageCover: "/images/tea/tra-sen-cover.png",
        description:
            "Trà sen Tây Hồ ướp sen Bách Diệp thơm ngát, mang hương vị truyền thống tinh tế.",
        category: "Trà Hương",
        popularity: 15,
        rating: 4.8,
    },
    {
        _id: "2",
        name: "Trà Ô Long Cao Cấp",
        brand: "Lộc Phát",
        images: ["/images/tea/tra-olong-thumb.jpg", "/images/tea/tra-olong-cover.jpg"],
        price: 180000,
        imageThumb: "/images/tea/tra-olong-thumb.png",
        imageCover: "/images/tea/tra-olong-cover.png",
        description:
            "Trà Ô Long tuyển chọn từ búp trà non, vị ngọt hậu, thanh mát và tốt cho sức khỏe.",
        category: "Trà Ô Long",
        popularity: 20,
        rating: 4.7,
    },
    {
        _id: "3",
        name: "Trà Xanh Thái Nguyên",
        brand: "Thái Nguyên",
        images: ["/images/tea/tra-xanh-thumb.jpg", "/images/tea/tra-xanh-cover.jpg"],
        price: 100000,
        imageThumb: "/images/tea/tra-xanh-thumb.jpg",
        imageCover: "/images/tea/tra-xanh-cover.jpg",
        description:
            "Trà xanh Thái Nguyên nổi tiếng với vị chát dịu, ngọt hậu, là thức uống quen thuộc.",
        category: "Trà Xanh",
        popularity: 10,
        rating: 4.5,
    },
    {
        _id: "4",
        name: "Trà Nhài",
        brand: "Hương Việt",
        images: ["/images/tea/tra-nhai-thumb.jpg", "/images/tea/tra-nhai-cover.jpg"],
        price: 90000,
        imageThumb: "/images/tea/tra-nhai-thumb.jpg",
        imageCover: "/images/tea/tra-nhai-cover.jpg",
        description:
            "Trà nhài với hương thơm thanh khiết, kết hợp vị chát nhẹ và mùi hoa nhài tự nhiên.",
        category: "Trà Hương",
        popularity: 12,
        rating: 4.6,
    },
    {
        _id: "5",
        name: "Trà Đen Assam",
        brand: "Highland Tea",
        images: ["/images/tea/tra-den-thumb.jpg", "/images/tea/tra-den-cover.jpg"],
        price: 150000,
        imageThumb: "/images/tea/tra-den-thumb.jpg",
        imageCover: "/images/tea/tra-den-cover.jpg",
        description:
            "Trà đen Assam có hương vị đậm đà, hậu vị ngọt, thường được dùng làm nền cho trà sữa.",
        category: "Trà Đen",
        popularity: 25,
        rating: 4.4,
    },
    {
        _id: "6",
        name: "Trà Matcha Nhật Bản",
        brand: "Uji Kyoto",
        images: ["/images/tea/matcha-thumb.jpg", "/images/tea/matcha-cover.jpg"],
        price: 250000,
        imageThumb: "/images/tea/matcha-thumb.jpg",
        imageCover: "/images/tea/matcha-cover.jpg",
        description:
            "Matcha cao cấp từ vùng Uji Kyoto, vị đậm đà, hậu ngọt, giàu chất chống oxy hóa.",
        category: "Matcha",
        popularity: 30,
        rating: 4.9,
    },
    {
        _id: "7",
        name: "Trà Thảo Mộc Hibiscus",
        brand: "Herbal House",
        images: [
            "/images/tea/hibiscus-thumb.jpg",
            "/images/tea/hibiscus-cover.jpg",
        ],
        price: 130000,
        imageThumb: "/images/tea/hibiscus-thumb.jpg",
        imageCover: "/images/tea/hibiscus-cover.jpg",
        description:
            "Trà hoa Hibiscus chua nhẹ, màu đỏ đẹp mắt, giúp thanh lọc cơ thể, tốt cho tim mạch.",
        category: "Trà Thảo Mộc",
        popularity: 18,
        rating: 4.3,
    },
    {
        _id: "8",
        name: "Trà Chai Ấn Độ",
        brand: "Spice Masala",
        images: ["/images/tea/chai-thumb.jpg", "/images/tea/chai-cover.jpg"],
        price: 160000,
        imageThumb: "/images/tea/chai-thumb.jpg",
        imageCover: "/images/tea/chai-cover.jpg",
        description:
            "Trà đen pha trộn cùng quế, gừng, thảo quả và sữa, mang đậm hương vị Ấn Độ.",
        category: "Trà Đen",
        popularity: 22,
        rating: 4.6,
    },
    {
        _id: "9",
        name: "Trà Bá Tước Earl Grey",
        brand: "Twinings",
        images: ["/images/tea/earl-grey-thumb.jpg", "/images/tea/earl-grey-cover.jpg"],
        price: 170000,
        imageThumb: "/images/tea/earl-grey-thumb.jpg",
        imageCover: "/images/tea/earl-grey-cover.jpg",
        description:
            "Trà Earl Grey pha với tinh dầu cam Bergamot, hương thơm sang trọng và thanh lịch.",
        category: "Trà Đen",
        popularity: 28,
        rating: 4.7,
    },
    {
        _id: "10",
        name: "Trà Hoa Cúc",
        brand: "Herbal House",
        images: ["/images/tea/hoa-cuc-thumb.jpg", "/images/tea/hoa-cuc-cover.jpg"],
        price: 110000,
        imageThumb: "/images/tea/hoa-cuc-thumb.jpg",
        imageCover: "/images/tea/hoa-cuc-cover.jpg",
        description:
            "Trà hoa cúc vàng dịu nhẹ, thanh mát, giúp an thần và hỗ trợ giấc ngủ sâu.",
        category: "Trà Thảo Mộc",
        popularity: 14,
        rating: 4.5,
    },
];
